import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import fs from "fs";
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import mongoose from "mongoose";
import dotenv from "dotenv";

dotenv.config();

// Fix for __dirname in ES Modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Ensure uploads directory exists
const UPLOADS_DIR = path.join(process.cwd(), "uploads");
if (!fs.existsSync(UPLOADS_DIR)) {
  fs.mkdirSync(UPLOADS_DIR);
}

// --- MONGODB CONNECTION ---
const MONGODB_URI = process.env.MONGODB_URI || "";

mongoose.connect(MONGODB_URI)
  .then(() => console.log("✅ MongoDB connected successfully"))
  .catch(err => console.error("❌ MongoDB connection error:", err));

// --- SCHEMAS (String-ID Compatible) ---
// We use _id: String to match the custom IDs generated by your frontend/SQLite logic
const UserSchema = new mongoose.Schema({
  _id: { type: String, required: true }, 
  firstName: String,
  lastName: String,
  mobileNumber: String,
  email: { type: String, unique: true, required: true },
  password: { type: String, required: true }
}, { _id: false });
const User = mongoose.model("User", UserSchema);

const ServiceSchema = new mongoose.Schema({
  _id: { type: String, required: true },
  state: String,
  town: String,
  category: String,
  providerName: String,
  description: String,
  contactNumber: String,
  operatingHours: String,
  photoUrls: [String],
  createdBy: String, // Stored as a String ID to link to User._id
  createdAt: { type: Number, default: () => Date.now() }
}, { _id: false });
const Service = mongoose.model("Service", ServiceSchema);

const RatingSchema = new mongoose.Schema({
  _id: { type: String, required: true },
  serviceId: String,
  userId: String,
  rating: Number,
  createdAt: { type: Number, default: () => Date.now() }
}, { _id: false });
const Rating = mongoose.model("Rating", RatingSchema);

// --- HELPERS ---
const saveBase64Image = (base64Str: string): string => {
  if (!base64Str || !base64Str.startsWith('data:image')) return base64Str;
  try {
    const matches = base64Str.match(/^data:([A-Za-z-+/]+);base64,(.+)$/);
    if (!matches || matches.length !== 3) return base64Str;
    const extension = matches[1].split('/')[1];
    const fileName = `${Math.random().toString(36).substring(2, 15)}.${extension}`;
    const filePath = path.join(UPLOADS_DIR, fileName);
    fs.writeFileSync(filePath, Buffer.from(matches[2], 'base64'));
    return `/uploads/${fileName}`;
  } catch (e) {
    console.error("Image save error:", e);
    return base64Str;
  }
};

// --- SERVER LOGIC ---
async function startServer() {
  const app = express();
  const PORT = process.env.PORT || 3000;

  app.use(express.json({ limit: '10mb' }));
  app.use("/uploads", express.static(UPLOADS_DIR));

  // --- AUTH ROUTES ---
  app.post("/api/auth/signup", async (req, res) => {
    try {
      const id = Math.random().toString(36).substring(2, 15);
      const user = new User({ ...req.body, _id: id });
      await user.save();
      res.json({ id: user._id, ...req.body });
    } catch (err: any) {
      res.status(400).json({ error: err.message });
    }
  });

  app.post("/api/auth/login", async (req, res) => {
    const { email, password } = req.body;
    try {
      const user = await User.findOne({ email, password });
      if (user) {
        res.json({ id: user._id, firstName: user.firstName, lastName: user.lastName, email: user.email });
      } else {
        res.status(401).json({ error: "Invalid credentials" });
      }
    } catch (err: any) {
      res.status(400).json({ error: err.message });
    }
  });

  // --- SERVICES ROUTES ---
  app.get("/api/services", async (req, res) => {
    const { state, town, category, search, createdBy } = req.query;
    let filter: any = {};
    if (state) filter.state = state;
    if (town) filter.town = town;
    if (category) filter.category = category;
    if (createdBy) filter.createdBy = createdBy;
    if (search) {
      filter.$or = [
        { providerName: new RegExp(search as string, 'i') },
        { description: new RegExp(search as string, 'i') }
      ];
    }

    try {
      const services = await Service.find(filter).sort({ createdAt: -1 });
      const formatted = await Promise.all(services.map(async (s: any) => {
        const ratings = await Rating.find({ serviceId: s._id });
        const avg = ratings.length ? ratings.reduce((acc, curr) => acc + curr.rating, 0) / ratings.length : 0;
        const owner = await User.findById(s.createdBy);
        
        return { 
          ...s.toObject(), 
          id: s._id, 
          avgRating: avg, 
          ratingCount: ratings.length,
          creatorName: owner ? `${owner.firstName} ${owner.lastName}` : "Unknown"
        };
      }));
      res.json(formatted);
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  app.post("/api/services", async (req, res) => {
    try {
      const { photoUrls, createdBy, ...data } = req.body;
      const id = Math.random().toString(36).substring(2, 15);
      const processedUrls = (photoUrls || []).map((url: string) => saveBase64Image(url));
      
      const service = new Service({ 
        ...data, 
        _id: id, 
        createdBy, 
        photoUrls: processedUrls,
        createdAt: Date.now()
      });
      await service.save();
      res.json({ ...service.toObject(), id: service._id });
    } catch (err: any) {
      res.status(400).json({ error: err.message });
    }
  });

  // --- VITE / PRODUCTION SETUP ---
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.join(__dirname, "dist")));
    app.get("*", (req, res) => {
      res.sendFile(path.join(__dirname, "dist", "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`🚀 Server running on port ${PORT}`);
  });
}

startServer();
